# Generated by Django 3.2.3 on 2021-05-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.AlterField(
            model_name='books',
            name='publishing_company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='books',
            name='release_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
